#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
	al_MainLoop.cpp \
	al_MainLoopGLUT.cpp \
	al_Printing.cpp \
	al_Time.cpp

CFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS

ifeq ($(PLATFORM), linux)
	LFLAGS += -lpthread
endif

ifeq ($(RUNTIME_BINDING), APR)
	SYS_SRC += al_ThreadAPR.cpp
else
	SYS_SRC += al_ThreadNative.cpp
endif
