#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
	al_MainLoop.cpp \
	al_MainLoopGLUT.cpp \
	al_Printing.cpp \
	al_Time.cpp

ifeq ($(PLATFORM), linux)
	LFLAGS += -lpthread
endif
