#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
#	al_Config.cpp \
	al_MainLoop.c \
	al_Printing.cpp \
	al_Time.c

ifeq ($(PLATFORM), linux)
	LFLAGS += -lpthread
endif
