#=========================================================================
# Allo Types makefile configuration
#=========================================================================

TYP_SRC = \
	al_Array_C.c \
	al_Array.cpp \
	al_Color.cpp \
	al_Conversion.cpp \
	al_MsgQueue.cpp \
	al_Voxels.cpp
