language: cpp
compiler:
 - gcc
 - clang
env:
      global:
           - VERBOSE=1
install:
 - apt-get install libapr1-dev libaprutil1-dev portaudio19-dev libsndfile1-dev libglew-dev freeglut3-dev libavahi-client-dev libudev-dev libusb-1.0-0-dev libfreeimage-dev libfreetype6-dev libxi-dev libxmu-dev
script: cmake . -DCMAKE_BUILD_TYPE=Debug && make && make test

notifications:
      email:
          recipients:
              - mantaraya36@gmail.com
