language: cpp
compiler:
 - gcc
 - clang
env:
      global:
           - VERBOSE=1
install: ./install_all_dependencies.sh
script: cmake . -DCMAKE_BUILD_TYPE=Debug && make && make test

notifications:
      email:
          recipients:
              - mantaraya36@gmail.com
