language: cpp
compiler:
- gcc
- clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libapr1-dev libaprutil1-dev portaudio19-dev libsndfile1-dev
  libglew-dev freeglut3-dev libavahi-client-dev libudev-dev libusb-1.0-0-dev libfreeimage-dev
  libfreetype6-dev libxi-dev libxmu-dev libassimp-dev libluajit-5.1-dev libjsoncpp-dev
script: "./distclean && cmake . -DCMAKE_BUILD_TYPE=Debug && make && make test"
sudo: required
notifications:
  email:
    recipients:
    - mantaraya36@gmail.com
