#!/bin/sh

# Since we were using the same line anyways...
cleaner="rm -rf build/ CMakeCache.txt CMakeFiles/ cmake_install.cmake Makefile build.ninja rules.ninja AlloSystem.xcodeproj AlloSystem.build CMakeScripts"

# Run in root directory.
eval "$cleaner"

# Run in almost all first level subdirectories.
for d in */ ; do
  # Except allonect, which still uses a Makefile.
  if [ "$d" = "allonect/" ]; then
    continue 
  else
    cd "$d"
      eval "$cleaner"
    cd ..
  fi
done

# Remove build files from our inter-operating libraries.
rm -rf ../GLV/AlloSystem-build

rm -rf ../Gamma/AlloSystem-build
