#rm build/bin/example
# -Wl,-r 
#g++ -DOSC_HOST_LITTLE_ENDIAN -Iinclude//allocore/types/jack/ -I/usr/include/ -Iinclude/ -Iosx/include/ -Ibuild//include -undefined dynamic_lookup -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -arch i386 -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5 -O3 -fpeel-loops -Wreturn-type -Wformat -Wmissing-braces -Wparentheses -Wswitch -Wunused-variable -Wsign-compare -Wno-unknown-pragmas  -Wnon-virtual-dtor -Woverloaded-virtual -force_load build/lib/liballocore.a -o build/bin/example examples/allojit/example.cpp -L/usr/lib/ -Losx/lib/ -Lbuild//lib -framework Carbon  -lapr-1 -lfreeimage -lassimp -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework Carbon -lportaudio -framework AGL -framework OpenGL -framework GLUT -lallojit -lalloutil
#g++ -Ibuild//include -I/usr/include/ -Iinclude/ -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -O3 -fpeel-loops -Wreturn-type -Wformat -Wmissing-braces -Wparentheses -Wswitch -Wunused-variable -Wsign-compare -Wno-unknown-pragmas  -Wnon-virtual-dtor -Woverloaded-virtual -Wl,--whole-archive -o build/bin/example examples/allojit/example.cpp -L/usr/lib/ -Llinux/lib/ -Lbuild//lib -lapr-1 -lfreeimage -lassimp -lportaudio -lglut -lGLEW -ljack -lallojit -lalloutil
#g++ -c -Wall -Ibuild//include -I/usr/include/ -Iinclude/ -Lbuild/lib -L/usr/lib -L/usr/local/lib -Wl,--whole-archive build/lib/liballocore.a build/lib/liballojit.a -Wl,--no-whole-archive examples/allojit/example.cpp -lglut -lapr-1 -lGLEW -lportaudio -ljack -lfreeimage -lassimp
#g++ -Lbuild/lib -L/usr/lib -L/usr/local/lib -Wl,--whole-archive build/lib/liballocore.a build/lib/liballojit.a -Wl,--no-whole-archive example.o -lglut -lapr-1 -lGLEW -lportaudio -ljack -lfreeimage -lassimp
#g++ -Lbuild/lib -L/usr/lib -L/usr/local/lib -rdynamic  -Wl,--whole-archive build/lib/liballocore.a -Wl,--no-whole-archive example.o build/lib/liballojit.a -lpthread -lstdc++ -ldl -lglut -lapr-1 -lGLEW -lportaudio -ljack -lfreeimage -o build/bin/example
#build/bin/example
#nm build/bin/example | grep _ZN2al8MainLoop3getEv


# this works for macosx:
g++ -Wall -Ibuild/include -Iinclude -Iosx/include -I/usr/include -I/usr/local/include -Lbuild/lib -Losx/lib -Losx/lib32/llvm -L/usr/lib -L/usr/local/lib -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -arch i386 -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5 -O3 -fno-rtti -force_load build/lib/liballocore.a -o build/bin/ajit src/allojit/al_Compiler.cpp src/allojit/ajit.cpp -framework Carbon -lapr-1 -lfreeimage -lassimp -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework Cocoa  -framework Carbon -lportaudio -framework AGL -framework OpenGL -framework GLUT -lalloutil -lclang -lclangAnalysis -lclangAST -lclangBasic -lclangChecker -lclangCodeGen -lclangDriver -lclangFrontend -lclangIndex -lclangLex -lclangParse -lclangRewrite -lclangSema -lclangSerialization -lCompilerDriver -lEnhancedDisassembly -lLLVMAnalysis -lLLVMArchive -lLLVMAsmParser -lLLVMAsmPrinter -lLLVMBitReader -lLLVMBitWriter -lLLVMCBackend -lLLVMCBackendInfo -lLLVMCodeGen -lLLVMCore -lLLVMCppBackend -lLLVMCppBackendInfo -lLLVMExecutionEngine -lLLVMInstCombine -lLLVMInstrumentation -lLLVMInterpreter -lLLVMipa -lLLVMipo -lLLVMJIT -lLLVMLinker -lLLVMMC -lLLVMMCDisassembler -lLLVMMCParser -lLLVMpic16passes -lLLVMScalarOpts -lLLVMSelectionDAG -lLLVMSupport -lLLVMSystem -lLLVMTarget -lLLVMTransformUtils -lLLVMX86AsmParser -lLLVMX86AsmPrinter -lLLVMX86CodeGen -lLLVMX86Disassembler -lLLVMX86Info