#=========================================================================
# Allo makefile configuration
#=========================================================================
#=========================================================================
# Uncomment your system -or- use command-line argument PLATFORM='platform'
#=========================================================================
PLATFORM = macosx
#PLATFORM = linux
#PLATFORM = windows


#=========================================================================
# Customize to fit your system
#=========================================================================
PREFIX     = /usr/local
CONFPREFIX = $(PREFIX)/etc
MANPREFIX  = $(PREFIX)/share/man

LIBS       = -L$(PREFIX)/lib -L/usr/lib

CFLAGS     = -I. -I$(PREFIX)/include -I/usr/include \
             -fPIC -O3 -fpeel-loops -Wall \
             -D__STDC_CONSTANT_MACROS

LFLAGS     = $(LIBS) -lm

SLIBFLAGS := -Wl,-single_module -compatibility_version 1 \
             -current_version 1

#-------------------------------------------------------------------------
# Default variables (may be overridden in platform specific section)
#-------------------------------------------------------------------------
AR         = ar cr
CC         = g++
INSTALL    = install
RANLIB     = ranlib
LIB_PREFIX = allo
ALIB_EXT   = a
SLIB_EXT   = so
SLIB_OPT   = shared

NET_DIR    = network
SYS_DIR    = system
TYPES_DIR  = types

#=========================================================================
# DO NOT EDIT BELOW!
#=========================================================================

#=========================================================================
# Platform specific section
#=========================================================================

#linux:
ifeq ($(PLATFORM), linux)
	LFLAGS  += -lrt
	CFLAGS  += -D__LINUX__
endif

#macosx:
ifeq ($(PLATFORM), macosx)
	LFLAGS	+= -framework Carbon
	SLIB_EXT = dylib
	SLIB_OPT = dynamiclib
endif

