#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
	al_Info.cpp \
	al_MainLoop.cpp \
	al_Printing.cpp \
	al_Time.cpp \
	al_Watcher.cpp
	
EXT_CPPFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS

ifeq ($(PLATFORM), linux)
	EXT_LDFLAGS += -lpthread
endif

ifeq ($(PLATFORM), macosx)
	SYS_SRC += al_MainLoopOSX.mm
	SYS_SRC += al_InfoOSX.mm
endif

ifeq ($(RUNTIME_BINDING), APR)
	SYS_SRC += al_ThreadAPR.cpp
else
	SYS_SRC += al_ThreadNative.cpp
endif
