#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

GFX_SRC = \
	al_Asset.cpp \
	al_Font.cpp \
	al_GPUObject.cpp \
	al_Graphics.cpp \
	al_GraphicsGL.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Light.cpp \
	al_Mesh.cpp \
	al_Model.cpp \
	al_Shader.cpp \
	al_Shapes.cpp \
	al_Stereographic.cpp \
	al_Surface.cpp \
	al_Texture.cpp

ifeq ($(IMAGE_BINDING), FreeImage)
	EXT_LDFLAGS += -lfreeimage
endif

EXT_LDFLAGS += -lassimp
EXT_LDFLAGS += -lfreetype
INC_DIRS +=	/usr/include/freetype2
