#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

ifeq ($(PLATFORM), linux)
	LFLAG_GLUT = -lglut
	LFLAGS_GL += -lGLEW -lGLU -lGL
	LFLAGS_AUDIO = -lrt -lasound -lpthread
endif

ifeq ($(PLATFORM), macosx)
	LFLAG_GLUT = -framework GLUT
	LFLAGS_GL += -framework AGL -framework OpenGL
	LFLAGS_AUDIO = -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework Carbon
endif

OBJ_WINDOW = ./src/al_WindowGL.o
LFLAGS_WINDOW = $(LFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	LFLAGS_WINDOW += $(LFLAG_GLUT)
	OBJ_WINDOW += ./src/al_WindowGLUT.o
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LFLAGS_AUDIO += -lportaudio
endif
