#=========================================================================
# AlloCore Protocol makefile configuration
#=========================================================================

include ../$(SYS_DIR)/Makefile.config

OSC_DIR_INC = ../include/protocol/oscpack
OSC_DIR_SRC = ./src/oscpack
OSC_DIR_PF = posix

ifeq ($(PLATFORM), windows)
	OSC_DIR_PF = win32
endif

ifneq ($(BIG_ENDIAN), 0)
	OSC_CFLAGS = -DOSC_HOST_LITTLE_ENDIAN
else
	OSC_CFLAGS = -DOSC_HOST_BIG_ENDIAN
endif

OSC_CFLAGS += -I$(OSC_DIR_INC) -I$(OSC_DIR_INC)/ip -I$(OSC_DIR_INC)/osc

OSC_SRC = 	$(OSC_DIR_SRC)/IpEndpointName.cpp \
		$(OSC_DIR_SRC)/OscOutboundPacketStream.cpp \
		$(OSC_DIR_SRC)/OscPrintReceivedElements.cpp \
		$(OSC_DIR_SRC)/OscReceivedElements.cpp \
		$(OSC_DIR_SRC)/OscTypes.cpp \
		$(OSC_DIR_SRC)/$(OSC_DIR_PF)/NetworkingUtils.cpp \
		$(OSC_DIR_SRC)/$(OSC_DIR_PF)/UdpSocket.cpp \
		src/al_OSC.cpp

OSC_OBJ = $(OSC_SRC:.cpp=.o)
