#=========================================================================
# Allo Network makefile configuration
#=========================================================================

include ../$(SYS_DIR)/Makefile.config

OSC_DIR = ../$(NET_DIR)/ext/oscpack
OSC_DIR_SRC = $(OSC_DIR)/src
OSC_DIR_PF = posix

ifeq ($(PLATFORM), windows)
	OSC_SRC_PF = win32
endif

CFLAGS += -I../$(NET_DIR)/include -I$(OSC_DIR)/include/ -I$(OSC_DIR)/include/ip -I$(OSC_DIR)/include/osc

OSC_SRC = 	$(OSC_DIR_SRC)/IpEndpointName.cpp \
		$(OSC_DIR_SRC)/OscOutboundPacketStream.cpp \
		$(OSC_DIR_SRC)/OscPrintReceivedElements.cpp \
		$(OSC_DIR_SRC)/OscReceivedElements.cpp \
		$(OSC_DIR_SRC)/OscTypes.cpp \
		$(OSC_DIR_SRC)/$(OSC_DIR_PF)/NetworkingUtils.cpp \
		$(OSC_DIR_SRC)/$(OSC_DIR_PF)/UdpSocket.cpp \
		src/OSC.cpp
