#=========================================================================
# Allo Types makefile configuration
#=========================================================================

JACK_DIR_INC = $(INC_DIR)/allocore/types/jack/
JACK_DIR_SRC = jack/
JACK_SRC = $(JACK_DIR_SRC)ringbuffer.c

JACK_CPPFLAGS = -I$(JACK_DIR_INC)

TYP_SRC = \
	al_Color.cpp \
	al_MsgQueue.cpp \
	$(JACK_SRC)
	
VPATH += $(addprefix $(SRC_DIR)$(TYP_DIR), $(JACK_DIR_SRC))
CPPFLAGS += $(JACK_CPPFLAGS)



