#=========================================================================
# AlloCore spatial makefile configuration
#=========================================================================

SPA_SRC = 	al_Camera.cpp \
		al_HashSpace.cpp \
		al_Pose.cpp

