#=========================================================================
# AlloCore Sound makefile configuration
#=========================================================================

SND_SRC = 	al_Ambisonics.cpp \
		al_AudioScene.cpp \
		al_Dbap.cpp \
		al_Vbap.cpp
