#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

GFX_SRC = \
	al_Debug.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Light.cpp \
	al_Model.cpp \
	al_Debug.cpp \
	al_Stereographic.cpp \
	al_Surface.cpp \
	al_Texture.cpp \
	al_Shader.cpp

ifeq ($(IMAGE_BINDING), FreeImage)
	EXT_LDFLAGS += -lfreeimage
endif
