#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

GFX_SRC = \
	al_Debug.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Light.cpp \
	al_Model.cpp \
	al_Debug.cpp \
	al_Stereographic.cpp \
	al_Surface.cpp \
	al_Texture.cpp \
	al_Shader.cpp \
	al_ShaderAttribute.cpp \
	al_ShaderBackend.cpp \
	al_ShaderBackendGLSL.cpp \
	al_ShaderParam.cpp \
	al_ShaderProgram.cpp 

