#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

GFX_SRC = \
	al_Context.cpp \
	al_Debug.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Light.cpp \
	al_Model.cpp \
	al_Shader.cpp \
	al_Debug.cpp \
	al_Stereographic.cpp \
	al_Surface.cpp \
	al_Texture.cpp

