#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
	al_config.cpp \
	al_MainLoop.c \
	al_Time.c

ifeq ($(PLATFORM), linux)
	LFLAGS += -lpthread
endif