#=========================================================================
# Allo System makefile configuration
#=========================================================================

CFLAGS += -I../$(SYS_DIR)/include

ifeq ($(PLATFORM), linux)
	LFLAGS += -lpthread
endif