#=========================================================================
# AlloCore Protocol makefile configuration
#=========================================================================

# OSC classes depend on Thread...
#include ../$(SYS_DIR)Makefile.config

OSC_DIR_SRC = oscpack/
OSC_DIR_PF = posix/
OSC_CPPFLAGS = -DOSC_HOST_LITTLE_ENDIAN

ifeq ($(PLATFORM), windows)
	OSC_DIR_PF = win32
endif

ifneq ($(BIG_ENDIAN), 0)
	OSC_CPPFLAGS = -DOSC_HOST_BIG_ENDIAN
endif

OSC_SRC = \
	$(OSC_DIR_SRC)osc/OscOutboundPacketStream.cpp \
	$(OSC_DIR_SRC)osc/OscPrintReceivedElements.cpp \
	$(OSC_DIR_SRC)osc/OscReceivedElements.cpp \
	$(OSC_DIR_SRC)osc/OscTypes.cpp

# IP sources not needed since using al::Socket
#OSC_SRC += \
#	$(OSC_DIR_SRC)ip/IpEndpointName.cpp \
#	$(OSC_DIR_SRC)ip/$(OSC_DIR_PF)NetworkingUtils.cpp \
#	$(OSC_DIR_SRC)ip/$(OSC_DIR_PF)UdpSocket.cpp \

PRO_SRC = \
	$(OSC_SRC) \
	al_OSC.cpp \
	al_XML.cpp \
	al_Serialize.cpp 

# TODO: zeroconf support for Windows
ifeq ($(PLATFORM), macosx)
	PRO_SRC += al_Zeroconf_OSX.mm
else ifeq ($(PLATFORM), linux)
	PRO_SRC += al_Zeroconf.cpp
endif

ifeq ($(PLATFORM), linux)
	LINK_LDFLAGS += -lavahi-client
endif

CPPFLAGS += $(OSC_CPPFLAGS)
VPATH += $(addprefix $(SRC_DIR)$(PRO_DIR), $(OSC_DIR_SRC)osc/)
