#=========================================================================
# Allo System makefile configuration
#=========================================================================

SYS_SRC = \
	al_Info.cpp \
	al_MainLoop.cpp \
	al_OS.cpp \
	al_PeriodicThread.cpp \
	al_Printing.cpp \
	al_Thread.cpp \
	al_ThreadPool.cpp \
	al_Time.cpp \
	al_Watcher.cpp

LINK_CPPFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS

ifeq ($(PLATFORM), linux)
	LINK_LDFLAGS += -lpthread

else ifeq ($(PLATFORM), macosx)
	SYS_SRC += al_MainLoopOSX.mm
	SYS_SRC += al_InfoOSX.mm
	LINK_LDFLAGS += -lpthread
	LINK_LDFLAGS += -framework Cocoa -framework Foundation
endif
