#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

USE_FONT ?= 1

GFX_SRC = \
	al_BufferObject.cpp \
	al_FBO.cpp \
	al_GPUObject.cpp \
	al_Graphics.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Lens.cpp \
	al_Light.cpp \
	al_Mesh.cpp \
	al_Screenshot.cpp \
	al_Shader.cpp \
	al_Shapes.cpp \
	al_Stereoscopic.cpp \
	al_Texture.cpp

ifeq ($(USE_FONT), 1)

	GFX_SRC += al_Font.cpp
	LINK_LDFLAGS += -lfreetype

	ifeq ($(PLATFORM), linux)
		INC_DIRS += /usr/include/freetype2

	else ifeq ($(PLATFORM), macosx)
		# With older versions of OS X, FreeType is in /usr/X11/ ...
		#ifdef HAS_USR_X11
		ifneq ($(wildcard /usr/X11/include/freetype2/),)
			LINK_LDFLAGS += -L/usr/X11/lib/
			INC_DIRS += /usr/X11/include/
			INC_DIRS += /usr/X11/include/freetype2/
		else ifdef HAS_OPT_LOCAL
			INC_DIRS += /opt/local/include/freetype2/
		else
			INC_DIRS += /usr/local/include/freetype2/
		endif

	else ifeq ($(PLATFORM), windows)
		INC_DIRS += $(PREFIX)/include/freetype2

	endif
endif
	
ifeq ($(IMAGE_BINDING), FreeImage)
	CPPFLAGS += -DAL_IMAGE_FREEIMAGE
	LINK_LDFLAGS += -lfreeimage
endif
