#=========================================================================
# Allo Graphics makefile configuration
#=========================================================================

GFX_SRC = \
	al_Asset.cpp \
	al_FBO.cpp \
	al_GPUObject.cpp \
	al_Graphics.cpp \
	al_Image.cpp \
	al_Isosurface.cpp \
	al_Lens.cpp \
	al_Light.cpp \
	al_Mesh.cpp \
	al_Shader.cpp \
	al_Shapes.cpp \
	al_Stereographic.cpp \
	al_Texture.cpp \
	al_Font.cpp

ifeq ($(IMAGE_BINDING), FreeImage)
	LINK_LDFLAGS += -lfreeimage
endif

LINK_LDFLAGS += -lassimp
LINK_LDFLAGS += -lfreetype

ifeq ($(PLATFORM), linux)
	INC_DIRS += /usr/include/freetype2

else ifeq ($(PLATFORM), macosx)
	# freetype
	LINK_LDFLAGS += -L/usr/X11/lib/
	INC_DIRS += /usr/X11/include/
	INC_DIRS += /usr/X11/include/freetype2/
	INC_DIRS += /opt/local/include/freetype2/

else ifeq ($(PLATFORM), windows)
	INC_DIRS += $(PREFIX)/include/freetype2

endif
