#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

IO_SRC = \
	al_AudioIO.cpp \
	al_WindowGL.cpp

ifeq ($(RUNTIME_BINDING), APR)
	IO_SRC += al_FileAPR.cpp al_SocketAPR.cpp
endif

ifeq ($(PLATFORM), linux)
	LFLAGS += -lrt
	LFLAG_GLUT = -lglut
	LFLAGS_GL += -lGLEW -lGLU -lGL
	LFLAGS_AUDIO = -lrt -lasound -lpthread
endif

ifeq ($(PLATFORM), macosx)
	LFLAG_GLUT = -framework GLUT
	LFLAGS_GL += $(addprefix -framework , AGL OpenGL)
	LFLAGS_AUDIO = $(addprefix -framework , AudioUnit AudioToolbox CoreAudio Carbon)
endif

ifeq ($(PLATFORM), windows)
	LFLAG_GLUT =
	LFLAGS_AUDIO =
endif

LFLAGS_WINDOW = $(LFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LFLAGS_WINDOW += $(LFLAG_GLUT)
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LFLAGS_AUDIO += -lportaudio
endif

LFLAGS += $(LFLAGS_AUDIO) $(LFLAGS_WINDOW)
