#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

IO_SRC = \
	al_AudioIO.cpp \
	al_File.cpp \
	al_Socket.cpp \
	al_WindowGL.cpp

ifeq ($(PLATFORM), linux)
	LFLAG_GLUT = -lglut
	LFLAGS_GL += -lGLEW -lGLU -lGL
	LFLAGS_AUDIO = -lrt -lasound -lpthread
endif

ifeq ($(PLATFORM), macosx)
	LFLAG_GLUT = -framework GLUT
	LFLAGS_GL += -framework AGL -framework OpenGL
	LFLAGS_AUDIO = -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework Carbon
endif

ifeq ($(PLATFORM), windows)
	LFLAG_GLUT =
	LFLAGS_AUDIO =
endif

LFLAGS_WINDOW = $(LFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LFLAGS_WINDOW += $(LFLAG_GLUT)
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LFLAGS_AUDIO += -lportaudio
endif

LFLAGS += $(LFLAGS_AUDIO) $(LFLAGS_WINDOW)
