#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

IO_SRC = \
	al_AudioIO.cpp \
	al_WindowGL.cpp

ifeq ($(RUNTIME_BINDING), APR)
	IO_SRC += al_FileAPR.cpp al_SocketAPR.cpp
endif

ifeq ($(PLATFORM), linux)
	LDFLAGS += -lrt
	LDFLAG_GLUT = -lglut
	LDFLAGS_GL = -lGLEW -lGLU -lGL
	LDFLAGS_AUDIO = -lrt -lasound -lpthread
endif

ifeq ($(PLATFORM), macosx)
	LDFLAG_GLUT = -framework GLUT
	LDFLAGS_GL = $(addprefix -framework , AGL OpenGL)
	LDFLAGS_AUDIO = $(addprefix -framework , AudioUnit AudioToolbox CoreAudio Carbon)
endif

ifeq ($(PLATFORM), windows)
	LDFLAG_GLUT =
	LDFLAGS_AUDIO =
endif

LDFLAGS_WINDOW = $(LDFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LDFLAGS_WINDOW += $(LDFLAG_GLUT)
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LDFLAGS_AUDIO += -lportaudio
endif

EXT_LDFLAGS += $(LDFLAGS_AUDIO) $(LDFLAGS_WINDOW)
