#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

IO_SRC = \
	al_App.cpp \
	al_AudioIO.cpp \
	al_File.cpp \
	al_HID.cpp \
	al_MIDI.cpp \
	al_Serial.cpp \
	al_Window.cpp \


ifeq ($(RUNTIME_BINDING), APR)
	IO_SRC += al_FileAPR.cpp al_SocketAPR.cpp
endif

IO_SRC += hidapi.c

ifeq ($(PLATFORM), linux)
	LDFLAGS += -lrt
	LDFLAG_GLUT = -lglut
	LDFLAGS_GL = -lGLEW -lGLU -lGL
	LDFLAGS_AUDIO = -lrt -lasound -lpthread
	LDFLAGS_HID = -lusb-1.0 `pkg-config libudev --libs`
	# INCLUDES ?= -I../hidapi `pkg-config libusb-1.0 --cflags`

else ifeq ($(PLATFORM), macosx)
	LDFLAG_GLUT = -framework GLUT
	LDFLAGS_GL = $(addprefix -framework , AGL OpenGL)
	LDFLAGS_AUDIO = $(addprefix -framework , AudioUnit AudioToolbox CoreAudio CoreMidi Carbon)
	LDFLAGS_HID = -framework IOKit -framework CoreFoundation

else ifeq ($(PLATFORM), windows)
	LDFLAG_GLUT = -lglut32
	LDFLAGS_GL = -lglew32 -lglu32 -lopengl32
	LDFLAGS_AUDIO =
	LDFLAGS_HID = -lsetupapi
	#LDFLAGS_HID += -mwindows # in hidapi Makfile, but breaks build
	
	# Req'd for Windows Sockets 2
	LINK_LDFLAGS += -lWs2_32
endif

LDFLAGS_WINDOW = $(LDFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LDFLAGS_WINDOW += $(LDFLAG_GLUT)
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LDFLAGS_AUDIO += -lportaudio
endif

LINK_LDFLAGS += $(LDFLAGS_AUDIO) $(LDFLAGS_WINDOW) $(LDFLAGS_HID)

