#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

IO_SRC = \
	al_App.cpp \
	al_AudioIO.cpp \
	al_File.cpp \
	al_MIDI.cpp \
	al_Serial.cpp \
	al_Window.cpp \


ifeq ($(RUNTIME_BINDING), APR)
	IO_SRC += al_FileAPR.cpp al_SocketAPR.cpp
endif

ifeq ($(PLATFORM), linux)
	LDFLAGS += -lrt
	LDFLAG_GLUT = -lglut
	LDFLAGS_GL = -lGLEW -lGLU -lGL
	LDFLAGS_AUDIO = -lrt -lasound -lpthread

else ifeq ($(PLATFORM), macosx)
	LDFLAG_GLUT = -framework GLUT
	LDFLAGS_GL = $(addprefix -framework , AGL OpenGL)
	LDFLAGS_AUDIO = $(addprefix -framework , AudioUnit AudioToolbox CoreAudio CoreMidi Carbon)

else ifeq ($(PLATFORM), windows)
	LDFLAG_GLUT = -lglut32
	LDFLAGS_GL = -lglew32 -lglu32 -lopengl32
	LDFLAGS_AUDIO =

	# Req'd for Windows Sockets 2
	LINK_LDFLAGS += -lWs2_32
endif

LDFLAGS_WINDOW = $(LDFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LDFLAGS_WINDOW += $(LDFLAG_GLUT)
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	LDFLAGS_AUDIO += -lportaudio
endif

LINK_LDFLAGS += $(LDFLAGS_AUDIO) $(LDFLAGS_WINDOW)

