#=========================================================================
# AlloCore IO makefile configuration
#=========================================================================

USE_HID  ?= 1
USE_MIDI ?= 1
USE_FILE ?= 1

IO_SRC = \
	al_App.cpp \
	al_AudioIOData.cpp \
	al_AudioIO.cpp \
	al_CSVReader.cpp \
	al_ControlNav.cpp \
	al_RenderToDisk.cpp \
	al_Serial.cpp \
	al_Socket.cpp \
	al_Window.cpp \

ifeq ($(USE_HID), 1)
	IO_SRC += hidapi.c al_HID.cpp
endif

ifeq ($(USE_MIDI), 1)
	IO_SRC += al_MIDI.cpp
endif

ifeq ($(USE_FILE), 1)
	IO_SRC += al_File.cpp
endif


ifeq ($(PLATFORM), linux)
	IO_SRC += al_Bluetooth.cpp

	LDFLAGS += -lrt
	LDFLAG_GLUT = -lglut
	LDFLAGS_GL = -lGLEW -lGLU -lGL
	LDFLAGS_AUDIO = -lrt -lasound -lpthread
	LDFLAGS_BT = -lbluetooth
	LDFLAGS_HID = `pkg-config libudev --libs`
	# If using libusb with HIDAPI
	#LDFLAGS_HID += -lusb-1.0
	#CPPFLAGS += `pkg-config libusb-1.0 --cflags`

else ifeq ($(PLATFORM), macosx)
	IO_SRC += al_BluetoothOSX.mm

	LDFLAG_GLUT = -framework GLUT
	LDFLAGS_GL = $(addprefix -framework , AGL OpenGL)
	LDFLAGS_AUDIO = $(addprefix -framework , AudioUnit AudioToolbox CoreAudio CoreMidi Carbon)
	LDFLAGS_BT = -framework IOBluetooth
	LDFLAGS_HID = -framework IOKit -framework CoreFoundation

else ifeq ($(PLATFORM), windows)
	IO_SRC += al_Bluetooth.cpp

	ifeq ($(MSYS_VERSION), 1)
		LDFLAG_GLUT = -lglut32
	else
		LDFLAG_GLUT = -lfreeglut
	endif
	LDFLAGS_GL = -lglew32 -lglu32 -lopengl32
	LDFLAGS_AUDIO = -lWinmm
	LDFLAGS_BT = -lbthprops
	LDFLAGS_FILE = -lShlwapi
	LDFLAGS_HID = -lSetupapi
	#LDFLAGS_HID += -mwindows # in hidapi Makefile, but breaks build

	# Use included headers to avoid having to install Windows SDK
	CPPFLAGS += -Isrc/io/bluetoothWindows/

	# Req'd for Windows Sockets 2
	LINK_LDFLAGS += -lWs2_32

else ifeq ($(PLATFORM), em)
	CPPFLAGS += -DAL_SOCKET_DUMMY
endif

LDFLAGS_WINDOW = $(LDFLAGS_GL)

ifeq ($(WINDOW_BINDING), GLUT)
	IO_SRC += al_WindowGLUT.cpp
	LDFLAGS_WINDOW += $(LDFLAG_GLUT)

else ifeq ($(WINDOW_BINDING), SDL)
	IO_SRC += al_WindowSDL.cpp
	LDFLAGS_WINDOW += -lSDL2main -lSDL2
	CPPFLAGS += -DAL_MAINLOOP_NO_GLUT

else ifeq ($(WINDOW_BINDING), native)
	ifeq ($(PLATFORM), macosx)
		IO_SRC += al_WindowOSX.mm
		# GLUT is deprecated in newer versions of OSX
		CPPFLAGS += -DAL_MAINLOOP_NO_GLUT
	endif
endif

ifeq ($(AUDIO_BINDING), PortAudio)
	CPPFLAGS += -DAL_AUDIO_PORTAUDIO
	LDFLAGS_AUDIO += -lportaudio

else ifeq ($(AUDIO_BINDING), SDL)
	CPPFLAGS += -DAL_AUDIO_SDL
	LDFLAGS_AUDIO += -lSDL2

else
	CPPFLAGS += -DAL_AUDIO_DUMMY
endif

LINK_LDFLAGS += $(LDFLAGS_AUDIO) $(LDFLAGS_WINDOW) $(LDFLAGS_BT) $(LDFLAGS_FILE) $(LDFLAGS_HID)

