#=========================================================================
# AlloUtil makefile configuration
#=========================================================================

UTIL_SRC = \
	al_FileWatcher.cpp \
	al_ResourceManager.cpp \
	al_WarpBlend.cpp

ifeq ($(PLATFORM), linux)
	LDFLAGS_UTIL += -llua5.1

else ifeq ($(PLATFORM), macosx)
	LDFLAGS_UTIL += -llua

else ifeq ($(PLATFORM), windows)
	LDFLAGS_UTIL += -llua
endif

LINK_LDFLAGS += $(LDFLAGS_UTIL)

